from typing import Protocol, runtime_checkable


@runtime_checkable
class Notifier(Protocol):
    async def publish(self, event_type: str, payload: dict) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
